---
application:
  name: "bubblesapi"
  project: "bubbles-api"
  organization: "QoveryCommunity"
  publicly_accessible: true
  port: 8080
routers:
- name: "main-bubblesapi"
  routes:
  - application_name: "bubblesapi"
    paths:
    - "/*"
